# Generated by Django 3.0.7 on 2020-07-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=29.9, max_digits=100)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=29.9, max_digits=100, null=True)),
                ('slug', models.SlugField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
