# Generated by Django 3.0.7 on 2020-07-23 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_cartitem_notee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='notee',
            new_name='notes',
        ),
    ]
